// Generates src/lib/config/glyphs.ts from the `simple-icons` package (CC0): only the icons that
// src/lib/config/{stack,channels}.ts reference, so client bundles don't ship the whole package.
// Run: node scripts/gen-glyphs.mts   (config.test.ts fails if the file is stale)
import { writeFileSync } from "node:fs";
import * as si from "simple-icons";
import { CHANNEL_LIST } from "../src/lib/config/channels.ts";
import { STACK_LIST } from "../src/lib/config/stack.ts";

const lum = (hex: string) => {
  const c = [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);
  const f = (v: number) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4);
  return 0.2126 * f(c[0]) + 0.7152 * f(c[1]) + 0.0722 * f(c[2]);
};
const contrast = (a: string, b: string) => {
  const [x, y] = [lum(a), lum(b)].sort((m, n) => n - m);
  return (x + 0.05) / (y + 0.05);
};
// Chip background (--secondary) per theme; brand colour kept only when it reads at 3:1.
const DARK_BG = "18181b";
const LIGHT_BG = "f4f4f5";

const slugs = [
  ...new Set(
    [...STACK_LIST, ...CHANNEL_LIST]
      .map((i) => ("simpleIcon" in i ? i.simpleIcon : undefined))
      .filter((x): x is string => Boolean(x)),
  ),
].sort();

const rows = slugs.map((slug) => {
  const icon = (si as Record<string, { title: string; hex: string; path: string }>)[
    `si${slug[0].toUpperCase()}${slug.slice(1)}`
  ];
  if (!icon) throw new Error(`missing simple icon ${slug}`);
  const fgDark = contrast(icon.hex, DARK_BG) >= 3 ? `#${icon.hex}` : "#ededed";
  const fgLight = contrast(icon.hex, LIGHT_BG) >= 3 ? `#${icon.hex}` : "#18181b";
  return `  ${JSON.stringify(slug)}: {\n    title: ${JSON.stringify(icon.title)},\n    fgDark: "${fgDark}",\n    fgLight: "${fgLight}",\n    path: ${JSON.stringify(icon.path)},\n  },`;
});

writeFileSync(
  "src/lib/config/glyphs.ts",
  `// GENERATED by scripts/gen-glyphs.mts from simple-icons (CC0-1.0). Do not edit by hand.
// Logos are trademarks of their owners, shown only to name the tool a project uses.
// fgDark/fgLight: the brand colour when it has >= 3:1 contrast on that theme's chip, else a
// neutral (spec 4.4: dark brands such as X, Vercel, Next.js render light on our dark UI).

export type Glyph = { title: string; fgDark: string; fgLight: string; path: string };

export const GLYPHS: Record<string, Glyph> = {
${rows.join("\n")}
};
`,
);
console.log(`wrote ${rows.length} glyphs`);
